### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by lesliechw** [ephraim/node-red-contrib-fprint#2]
Hi,

I get the following error when I try to run the install command (npm install node-red-contrib-fprint). What I did wrong? Please advice, thank you. Regards, Les:

```
pi@raspberrypi:~/.node-red $ npm install node-red-contrib-fprint

> node-fprint@0.0.9 install /home/pi/.node-red/node_modules/node-fprint
> node-gyp rebuild

Package libfprint was not found in the pkg-config search path.
Perhaps you should add the directory containing `libfprint.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libfprint' found
gyp: Call to 'pkg-config --libs libfprint' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-fprint
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-fprint@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-fprint@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-08-22T07_06_08_919Z-debug.log
```

**Comment by ephraim** [comment]
Hi!
You need to install the development files of libfprint.
For Ubuntu this can be done via something like:
sudo apt install libfprint-dev

Cheers
Thilo

**Comment by lesliedoghouse** [comment]
Hi thanks. I'm able to install already. Will try my U.are.U 4000B USB attach to RPi3.

Any documentation on how to use your nodes? Looking forward. Thanks.

**Comment by lesliedoghouse** [comment]
I import the sample flow, but no idea how to initialise the device and connect to it. Please advice, thank you.

**Comment by ephraim** [comment]
Just have a look at the node-fprint test scripts to get a better understanding how the node-red nodes can be used.
https://github.com/ephraim/node-fprint/tree/master/test/

**Comment by FabioSierra** [comment]
Hello everyone, thank you very much for sharing your work

I am trying to install on a raspberry pi 4 using the command "npm install node-red-contrib-fprint" and I am getting the following error

I appreciate the help


> pi@raspberrypi:~ $ npm install node-red-contrib-fprint
> node-fprint@0.0.9 install /home/pi/node_modules/node-fprint
> node-gyp rebuild
make: Entering directory '/home/pi/node_modules/node-fprint/build'
  CXX(target) Release/obj.target/fingerprint/src/enroll.o
  CXX(target) Release/obj.target/fingerprint/src/verify.o
../src/verify.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE verifyStart(Nan::NAN  _METHOD_ARGS_TYPE)’:
../src/verify.cpp:160:46: error: no matching function for call to ‘v8::Value::To  String()’
     s = *String::Utf8Value(info[1]->ToString());
                                              ^
In file included from /home/pi/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/fingerprint.h:1,
                 from ../src/verify.cpp:1:
/home/pi/.cache/node-gyp/12.18.4/include/node/v8.h:2668:44: note: candidate: ‘v8  ::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/pi/.cache/node-gyp/12.18.4/include/node/v8.h:2668:44: note:   candidate ex  pects 1 argument, 0 provided
In file included from /home/pi/.cache/node-gyp/12.18.4/include/node/v8-internal.  h:14,
                 from /home/pi/.cache/node-gyp/12.18.4/include/node/v8.h:27,
                 from /home/pi/.cache/node-gyp/12.18.4/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/fingerprint.h:1,
                 from ../src/verify.cpp:1:
/home/pi/.cache/node-gyp/12.18.4/include/node/v8.h:2684:31: note: candidate: ‘v8  ::Local<v8::String> v8::Value::ToString(v8::Isolate*) const’
                 Local<String> ToString(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definit  ion of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.18.4/include/node/v8.h:2684:31: note:   candidate ex  pects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.cache/node-gyp/12.18.4/include/node/v8config.h:328:3: note: in definit  ion of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [fingerprint.target.mk:116: Release/obj.target/fingerprint/src/verify.  o] Error 1
make: Leaving directory '/home/pi/node_modules/node-fprint/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module  s/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces  s.js:275:12)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy  p/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/node-fprint
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-fprint@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-fprint@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log  ging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-10-27T16_29_06_333Z-debug.log
