### ISSUE TITLE
npm ERR! Failed at the node-fprint@0.0.9 install script.

### ISSUE THREAD

**Issue by ndgspn** [ephraim/node-red-contrib-fprint#5]
Hello,

I'm stuck with this error below when installing node-red-contrib-fprint. `libfprint-dev` has been installed with command `sudo apt install libfprint-dev`.

Need help! thank you.

```
syspc@001:~$ npm install node-red-contrib-fprint -g

> node-fprint@0.0.9 install /home/syspc/.nvm/versions/node/v13.6.0/lib/node_modules/node-red-contrib-fprint/node_modules/node-fprint
> node-gyp rebuild

make: Entering directory '/home/syspc/.nvm/versions/node/v13.6.0/lib/node_modules/node-red-contrib-fprint/node_modules/node-fprint/build'
  CXX(target) Release/obj.target/fingerprint/src/enroll.o
  CXX(target) Release/obj.target/fingerprint/src/verify.o
../src/verify.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE verifyStart(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/verify.cpp:160:46: error: no matching function for call to ‘v8::Value::ToString()’
     s = *String::Utf8Value(info[1]->ToString());
                                              ^
In file included from /home/syspc/.cache/node-gyp/13.6.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/fingerprint.h:1,
                 from ../src/verify.cpp:1:
/home/syspc/.cache/node-gyp/13.6.0/include/node/v8.h:2750:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/syspc/.cache/node-gyp/13.6.0/include/node/v8.h:2750:44: note:   candidate expects 1 argument, 0 provided
fingerprint.target.mk:118: recipe for target 'Release/obj.target/fingerprint/src/verify.o' failed
make: *** [Release/obj.target/fingerprint/src/verify.o] Error 1
make: Leaving directory '/home/syspc/.nvm/versions/node/v13.6.0/lib/node_modules/node-red-contrib-fprint/node_modules/node-fprint/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/syspc/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/home/syspc/.nvm/versions/node/v13.6.0/bin/node" "/home/syspc/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/syspc/.nvm/versions/node/v13.6.0/lib/node_modules/node-red-contrib-fprint/node_modules/node-fprint
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-fprint@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-fprint@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/syspc/.npm/_logs/2020-01-23T07_33_23_141Z-debug.log
```

**Comment by ndgspn** [comment]
[SOLVED] - Use nodejs v10.x , not compatible with nodejs latest version.
